

///***************************************************************  空心心形 11x8 **************************************************************************/

#define SMALL_WIGHT_LOVE_0 0X00,0X00,0X00,
#define SMALL_WIGHT_LOVE_1 0X7D,0X17,0X43,

const unsigned char love_picture[][264]={{SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0
                                    SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0
                                    SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1
                                    SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0
                                    SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0
                                    SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0
                                    SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0
                                    SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0},
                                    
                                    {SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0
                                    SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0
                                    SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0
                                    SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0
                                    SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0
                                    SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0
                                    SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0
                                    SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0
                                    },
                                    
                                    {SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0
                                    SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0
                                    SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0
                                    SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0
                                    SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0
                                    SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0
                                    SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_1  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0
                                    SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0  SMALL_WIGHT_LOVE_0}};


///***************************************************************  温度计icon 6X8  **************************************************************************/


#define TEMPUTER_ICON_COLOR_0   0X00,0X00,0X00,
#define TEMPUTER_ICON_COLOR_1   0X88,0X88,0X88,
#define TEMPUTER_ICON_COLOR_2   0x82,0x14,0x14,

const unsigned char Temputer_icon_pic[][144]={{TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_1
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_1
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0},
                                            
                                            {TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_1
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_1
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0},
                                            
                                            {TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_1
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_1
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0},
                                            
                                            {TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_1
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_2  TEMPUTER_ICON_COLOR_1
                                            TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_0  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_1  TEMPUTER_ICON_COLOR_0}
                                            };

///***************************************************************  水滴5X6  **************************************************************************/

#define TEMPUTER_ICON_SHI_0 0X00,0X00,0X00,
#define TEMPUTER_ICON_SHI_1 0X88,0X88,0X88,
#define TEMPUTER_ICON_SHI_2 0X1B,0X47,0X87,

const unsigned char Temputer_icon_shi[][90] = {{TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_0
                                            TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_0
                                            TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_0
                                            TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_1
                                            TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_1
                                            TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_0},
                                            
                                            {TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_0
                                            TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_0
                                            TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_0
                                            TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_1
                                            TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_1
                                            TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_0},
                                            
                                            {TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_0
                                            TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_0
                                            TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_0
                                            TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_1
                                            TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_2  TEMPUTER_ICON_SHI_1
                                            TEMPUTER_ICON_SHI_0  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_1  TEMPUTER_ICON_SHI_0}
                                            };


///***************************************************************  喷水鲸鱼12X8  **************************************************************************/

#define SMALL_WIG_FISH_0 0X00,0X00,0X00,
#define SMALL_WIG_FISH_1 0X88,0X88,0X88,
#define SMALL_WIG_FISH_2 0X20,0X52,0X96,


const unsigned char SmallWig_Fish[][288]={{SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0},
  
                                        {SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0},
  
                                        {SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0},
  
                                        {SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0},
  
                                        {SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0},
  
                                        {SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0},
                                        
                                        {SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0},
                                        
                                        {SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0},
                                        
                                        {SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0},
                                        
                                        {SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0},
                                        
                                        {SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0
                                        SMALL_WIG_FISH_0  SMALL_WIG_FISH_0  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_1  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_2  SMALL_WIG_FISH_0  SMALL_WIG_FISH_0}
                                        };



const unsigned int test_picture[]  = {
  0x800000, 0x800000, 0x800000, 0x800000, 0x800000, 
  0x800000, 0x800000, 0x800000, 0x800000, 0x800000, 
  0x808080, 0x808080, 0x808080, 0x808080, 0x808080, 
  0x808080, 0x000000, 0x000000, 0x000000, 0x808080, 
  0x808080, 0x000000, 0x808080, 0x000000, 0x808080, 
  0x808080, 0x000000, 0x808080, 0x000000, 0x808080, 
  0x808080, 0x000000, 0x000000, 0x000000, 0x808080, 
  0x808080, 0x808080, 0x808080, 0x808080, 0x808080
};


const unsigned int SmallWight_AlarmClock[] = {
  0x787200, 0x787200, 0x787200, 0x000000, 0x787200, 0x787200, 0x787200, 
  0x787200, 0x314966, 0x314966, 0x314966, 0x314966, 0x314966, 0x787200, 
  0x000000, 0x314966, 0x000000, 0x031e70, 0x000000, 0x314966, 0x000000, 
  0x000000, 0x314966, 0x000000, 0x031e70, 0x031e70, 0x314966, 0x000000, 
  0x000000, 0x314966, 0x000000, 0x000000, 0x000000, 0x314966, 0x000000, 
  0x000000, 0x314966, 0x314966, 0x314966, 0x314966, 0x314966, 0x000000, 
  0x000000, 0x031e70, 0x000000, 0x000000, 0x000000, 0x031e70, 0x000000
};


